server:
  port: 8080
  servlet:
    context-path: /

wishlist:
  firebase:
    service-account-filename: service_account_key.json
    cloud-firestore-url: https://cst438-project2-ae257-default-rtdb.firebaseio.com

spring:
  profiles:
    active: dev
  jackson:
    time-zone: America/New_York

logging:
  level:
    root: info
